#!/usr/bin/env node

const asciidoctor = require('asciidoctor.js')()
require('asciidoctor-reveal.js')

const bs = require('browser-sync').create()

function build (adoc) {
  console.log('[present] building', adoc.replace('.adoc', '.html'), 'from', adoc)
  asciidoctor.convertFile(adoc, {
    safe: 'safe',
    backend: 'revealjs',
    attributes: {
      'revealjsdir': '/node_modules/reveal.js',
      'revealjs_theme': 'solarized',

      'source-highlighter': 'highlightjs',
      'highlightjs-theme': '/node_modules/highlight.js/styles/solarized-light.css'
    }
  })
}

const glob = require('glob')
glob('*/index.adoc', function (err, files) {
  if (err) throw err
  files.forEach(build)
})

// reload when index.html files change
bs.watch('*/index.html').on('change', bs.reload)

// build index.html when index.adoc files change
bs.watch('*/index.adoc').on('change', build)

// start the server
bs.init({
  directory: true,
  notify: false,
  open: false,
  server: true,
  ui: false
})
